browser: chrome
mode: single

specs:
    - Spec/Assignment.rb

dimensions:
   horizontal: 1280
   vertical: 960

switches:
  - disable-infobars
  - headless
  - window-size=1280,1024
  - window-size=1200,960
  - --use-fake-ui-for-media-stream
  - --incognito